using Inventory_Management.Application.DTOs.Report;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Inventory_Management.Application.Services;

public static class CompositePdfGenerator
{
    public static byte[] Generate(
        string tenantName,
        string userName,
        DateTime start,
        DateTime end,
        DashboardReportDto dashboard,
        SalesReportDto sales,
        PurchasesReportDto purchases,
        InventoryReportDto inventory)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(1.5f, Unit.Centimetre);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x.FontSize(9).FontFamily(Fonts.Arial));

                page.Header().Element(c => ComposeHeader(c, tenantName, userName, start, end));
                page.Content().Element(c => ComposeContent(c, dashboard, sales, purchases, inventory));
                page.Footer().Element(ComposeFooter);
            });
        });

        return document.GeneratePdf();
    }

    private static void ComposeHeader(IContainer container, string tenantName, string userName, DateTime start, DateTime end)
    {
        container.Row(row =>
        {
            row.RelativeItem().Column(column =>
            {
                column.Item().Text(string.IsNullOrWhiteSpace(tenantName) ? "Inventory Management System" : tenantName)
                    .FontSize(18).SemiBold().FontColor("#0B1F2E");
                
                column.Item().PaddingBottom(5).Text("Inventory & Financial Report")
                    .FontSize(20).Bold().FontColor("#0E8C7F");
                
                column.Item().Text($"Reporting Period: {start:MMM dd, yyyy} - {end:MMM dd, yyyy}").FontColor(Colors.Grey.Darken2);
                column.Item().Text($"Generated: {DateTime.Now:MMM dd, yyyy HH:mm}").FontColor(Colors.Grey.Darken2);
                column.Item().Text($"Generated By: {userName}").FontColor(Colors.Grey.Darken2);
            });
        });
    }

    private static void ComposeContent(IContainer container, DashboardReportDto dashboard, SalesReportDto sales, PurchasesReportDto purchases, InventoryReportDto inventory)
    {
        container.PaddingVertical(1, Unit.Centimetre).Column(column =>
        {
            column.Spacing(20);

            // 1. Executive Summary
            column.Item().Text("Executive Summary").FontSize(14).Bold().FontColor("#0B1F2E");
            column.Item().Element(c => ComposeDashboard(c, dashboard));

            // 2. Sales Table
            column.Item().EnsureSpace().Text("Sales Detail").FontSize(14).Bold().FontColor("#0B1F2E");
            column.Item().Element(c => ComposeSalesTable(c, sales));

            // 3. Purchases Table
            column.Item().EnsureSpace().Text("Purchases Detail").FontSize(14).Bold().FontColor("#0B1F2E");
            column.Item().Element(c => ComposePurchasesTable(c, purchases));

            // 4. Inventory Table
            column.Item().EnsureSpace().Text("Current Inventory").FontSize(14).Bold().FontColor("#0B1F2E");
            column.Item().Element(c => ComposeInventoryTable(c, inventory));
        });
    }

    private static void ComposeDashboard(IContainer container, DashboardReportDto dashboard)
    {
        container.Row(row =>
        {
            row.Spacing(10);
            
            // Total Sales, Revenue, Purchases
            row.RelativeItem().Column(c =>
            {
                c.Item().Text("Total Sales").FontSize(8).FontColor(Colors.Grey.Darken1);
                c.Item().Text($"ETB {dashboard.TotalSales.Value:N2}").FontSize(12).Bold();
            });
            row.RelativeItem().Column(c =>
            {
                c.Item().Text("Total Revenue").FontSize(8).FontColor(Colors.Grey.Darken1);
                c.Item().Text($"ETB {dashboard.TotalProfit.Value:N2}").FontSize(12).Bold();
            });
            row.RelativeItem().Column(c =>
            {
                c.Item().Text("Total Purchases").FontSize(8).FontColor(Colors.Grey.Darken1);
                c.Item().Text($"ETB {dashboard.TotalPurchases.Value:N2}").FontSize(12).Bold();
            });
            
            // Items Sold, Active Customers, Low Stock
            row.RelativeItem().Column(c =>
            {
                c.Item().Text("Items Sold").FontSize(8).FontColor(Colors.Grey.Darken1);
                c.Item().Text($"{dashboard.TotalProductsSold.Value:N0}").FontSize(12).Bold();
            });
            row.RelativeItem().Column(c =>
            {
                c.Item().Text("Customers").FontSize(8).FontColor(Colors.Grey.Darken1);
                c.Item().Text($"{dashboard.TotalCustomers.Value:N0}").FontSize(12).Bold();
            });
            row.RelativeItem().Column(c =>
            {
                c.Item().Text("Low Stock Items").FontSize(8).FontColor(Colors.Grey.Darken1);
                c.Item().Text($"{dashboard.LowStockProducts:N0}").FontSize(12).Bold().FontColor("#E53E3E");
            });
        });
    }

    private static void ComposeSalesTable(IContainer container, SalesReportDto sales)
    {
        if (sales.Table.Items.Count == 0)
        {
            container.Text("No sales data available for this period.").Italic();
            return;
        }

        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn(2);
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            table.Header(header =>
            {
                string[] headers = { "Invoice #", "Date", "Customer", "Items", "Payment", "Total" };
                foreach (var col in headers)
                {
                    header.Cell().Background("#0B1F2E").Padding(4).Text(col).FontColor(Colors.White).Bold();
                }
            });

            var isAlternate = false;
            foreach (var row in sales.Table.Items)
            {
                string bg = isAlternate ? "#F8FAFC" : Colors.White;
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.InvoiceNumber);
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.Date.ToString("MM/dd/yyyy"));
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(string.IsNullOrWhiteSpace(row.Customer) ? "Walk-in" : row.Customer);
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.NumberOfItems.ToString());
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.PaymentMethod ?? "-");
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text($"ETB {row.TotalAmount:N2}");
                isAlternate = !isAlternate;
            }
        });
    }

    private static void ComposePurchasesTable(IContainer container, PurchasesReportDto purchases)
    {
        if (purchases.Table.Items.Count == 0)
        {
            container.Text("No purchases data available for this period.").Italic();
            return;
        }

        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn(2);
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            table.Header(header =>
            {
                string[] headers = { "PO Number", "Date", "Supplier", "Items", "Status", "Total" };
                foreach (var col in headers)
                {
                    header.Cell().Background("#0B1F2E").Padding(4).Text(col).FontColor(Colors.White).Bold();
                }
            });

            var isAlternate = false;
            foreach (var row in purchases.Table.Items)
            {
                string bg = isAlternate ? "#F8FAFC" : Colors.White;
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.PurchaseNumber);
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.PurchaseDate.ToString("MM/dd/yyyy"));
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.Supplier ?? "-");
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.NumberOfItems.ToString());
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.Status);
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text($"ETB {row.TotalAmount:N2}");
                isAlternate = !isAlternate;
            }
        });
    }

    private static void ComposeInventoryTable(IContainer container, InventoryReportDto inventory)
    {
        if (inventory.Table.Items.Count == 0)
        {
            container.Text("No inventory data available.").Italic();
            return;
        }

        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(2);
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            table.Header(header =>
            {
                string[] headers = { "Product", "SKU", "Category", "In Stock", "Status", "Value" };
                foreach (var col in headers)
                {
                    header.Cell().Background("#0B1F2E").Padding(4).Text(col).FontColor(Colors.White).Bold();
                }
            });

            var isAlternate = false;
            foreach (var row in inventory.Table.Items)
            {
                string bg = isAlternate ? "#F8FAFC" : Colors.White;
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.Product);
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.SKU);
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.Category ?? "-");
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.CurrentStock.ToString());
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text(row.StockStatus);
                table.Cell().Background(bg).BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(4).Text($"ETB {row.InventoryValue:N2}");
                isAlternate = !isAlternate;
            }
        });
    }

    private static void ComposeFooter(IContainer container)
    {
        container.AlignCenter().Text(x =>
        {
            x.Span("Page ");
            x.CurrentPageNumber();
            x.Span(" of ");
            x.TotalPages();
            x.Span($"  |  Generated on {DateTime.UtcNow:yyyy-MM-dd HH:mm UTC}").FontSize(8).FontColor(Colors.Grey.Medium);
        });
    }
}
