using System.Text;
using Inventory_Management.Application.DTOs.Report;

namespace Inventory_Management.Application.Services;

public static class CompositeExcelGenerator
{
    public static byte[] Generate(
        string tenantName,
        string userName,
        DateTime start,
        DateTime end,
        DashboardReportDto dashboard,
        SalesReportDto sales,
        PurchasesReportDto purchases,
        InventoryReportDto inventory)
    {
        var sb = new StringBuilder();
        sb.Append("""
            <?xml version="1.0"?>
            <?mso-application progid="Excel.Sheet"?>
            <Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
            """);

        void Row(IEnumerable<string> cells)
        {
            sb.Append("<Row>");
            foreach (var cell in cells)
                sb.Append($"<Cell><Data ss:Type=\"String\">{System.Security.SecurityElement.Escape(cell ?? "")}</Data></Cell>");
            sb.Append("</Row>");
        }

        // Summary Worksheet
        sb.Append("<Worksheet ss:Name=\"Executive Summary\"><Table>");
        Row(["Inventory & Financial Report"]);
        Row(["Tenant", string.IsNullOrWhiteSpace(tenantName) ? "Inventory Management System" : tenantName]);
        Row(["Generated By", userName]);
        Row(["Reporting Period", $"{start:yyyy-MM-dd} to {end:yyyy-MM-dd}"]);
        Row(["Generated At", DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm 'UTC'")]);
        Row([]);
        Row(["Metric", "Value"]);
        Row(["Total Sales", $"ETB {dashboard.TotalSales.Value:N2}"]);
        Row(["Total Revenue", $"ETB {dashboard.TotalProfit.Value:N2}"]);
        Row(["Total Purchases", $"ETB {dashboard.TotalPurchases.Value:N2}"]);
        Row(["Items Sold", dashboard.TotalProductsSold.Value.ToString()]);
        Row(["Active Customers", dashboard.TotalCustomers.Value.ToString()]);
        Row(["Low Stock Items", dashboard.LowStockProducts.ToString()]);
        sb.Append("</Table></Worksheet>");

        // Sales Worksheet
        sb.Append("<Worksheet ss:Name=\"Sales\"><Table>");
        Row(["Invoice #", "Date", "Customer", "Items", "Payment", "Total"]);
        foreach (var row in sales.Table.Items)
        {
            Row([
                row.InvoiceNumber,
                row.Date.ToString("yyyy-MM-dd"),
                string.IsNullOrWhiteSpace(row.Customer) ? "Walk-in" : row.Customer,
                row.NumberOfItems.ToString(),
                row.PaymentMethod ?? "-",
                row.TotalAmount.ToString("0.00")
            ]);
        }
        sb.Append("</Table></Worksheet>");

        // Purchases Worksheet
        sb.Append("<Worksheet ss:Name=\"Purchases\"><Table>");
        Row(["PO Number", "Date", "Supplier", "Items", "Status", "Total"]);
        foreach (var row in purchases.Table.Items)
        {
            Row([
                row.PurchaseNumber,
                row.PurchaseDate.ToString("yyyy-MM-dd"),
                row.Supplier ?? "-",
                row.NumberOfItems.ToString(),
                row.Status ?? "-",
                row.TotalAmount.ToString("0.00")
            ]);
        }
        sb.Append("</Table></Worksheet>");

        // Inventory Worksheet
        sb.Append("<Worksheet ss:Name=\"Inventory\"><Table>");
        Row(["Product", "SKU", "Category", "In Stock", "Status", "Value"]);
        foreach (var row in inventory.Table.Items)
        {
            Row([
                row.Product,
                row.SKU,
                row.Category ?? "-",
                row.CurrentStock.ToString(),
                row.StockStatus ?? "-",
                row.InventoryValue.ToString("0.00")
            ]);
        }
        sb.Append("</Table></Worksheet>");

        sb.Append("</Workbook>");
        return Encoding.UTF8.GetBytes(sb.ToString());
    }
}
